### ISSUE TITLE
SteamInput integration issue

### ISSUE THREAD

**Issue by KelsamGames** [rlabrecque/Steamworks.NET#271]
Getting this error:

```
System.Runtime.InteropServices.MarshalDirectiveException
  HResult=0x80131535
  Message=Method's type signature is not PInvoke compatible.
  Source=Steamworks.NET
  StackTrace:
   at Steamworks.NativeMethods.ISteamInput_GetDigitalActionData(IntPtr instancePtr, InputHandle_t inputHandle, InputDigitalActionHandle_t digitalActionHandle)
   at Steamworks.SteamInput.GetDigitalActionData(InputHandle_t inputHandle, InputDigitalActionHandle_t digitalActionHandle)
   ...
```

When using this: `InputDigitalActionData_t data = SteamInput.GetDigitalActionData(inputHandle, digitalActionHandles[digitalAction]);`

**Comment by rlabrecque** [comment]
Whoop, we determined this was solved in this right?

https://github.com/rlabrecque/Steamworks.NET/commit/2d8e525a51cef096bf97cf101e13354d0c7dfd66

**Comment by KelsamGames** [comment]
Yep :)
